openapi: 3.1.0
info:
  title: Walandoo API
  version: 1.0.0
  description: |
    REST API for the Walandoo e-commerce demo application.
servers:
  - url: /api
paths:
  /products/:
    get:
      summary: List all products
      operationId: listProducts
      tags:
        - Products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{id}/:
    get:
      summary: Retrieve a product by ID
      operationId: getProduct
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
        number:
          type: integer
        title:
          type: string
        price:
          type: number
          format: float
        description:
          type: string
        category:
          type: string
        image:
          type: string
        rating_rate:
          type: number
          format: float
        rating_count:
          type: integer
      required:
        - id
        - number
        - title
        - price
        - description
        - category
        - image
        - rating_rate
        - rating_count